"""Protocols (ports) for the root config command group."""

from __future__ import annotations

from typing import Any, Protocol

from untaped.config_schema import FieldDescriptor


class SettingsReader(Protocol):
    """Read-side surface used by config listing, get, and prompt-default flows."""

    def descriptor(self, key: str) -> FieldDescriptor: ...
    def descriptors(self) -> list[FieldDescriptor]: ...
    def setting_value(self, descriptor: FieldDescriptor) -> Any: ...
    def raw_setting_value(self, descriptor: FieldDescriptor) -> Any: ...
    def env_value_for(self, descriptor: FieldDescriptor) -> str | None: ...
    def provenance(self) -> dict[tuple[str, ...], str]: ...
    def profile_value_for(self, descriptor: FieldDescriptor, profile: str) -> Any: ...
    def profile_data(self, name: str) -> dict[str, Any] | None: ...
    def profile_names(self) -> list[str]: ...


class SettingsRepository(SettingsReader, Protocol):
    """Read + write surface used by ``SetSetting`` / ``UnsetSetting``."""

    def set_value(
        self, key: str, raw_value: str, *, profile: str | None = None, dry_run: bool = False
    ) -> str: ...
    def unset_value(
        self, key: str, *, profile: str | None = None, dry_run: bool = False
    ) -> tuple[bool, str]: ...


__all__ = ["SettingsReader", "SettingsRepository"]
