"""Public API for the untaped core and plugin platform."""

from untaped.cli import (
    ColumnsOption,
    FormatOption,
    ProfileOverrideOption,
    clamp_parallel,
    parse_kv_pairs,
    profile_override,
    report_errors,
    resolve_each,
)
from untaped.config_schema import (
    FieldDescriptor,
    find_descriptor,
    redact_secrets,
    secret_field_paths,
    walk_settings,
)
from untaped.errors import ConfigError, HttpError, UntapedError, first_validation_error
from untaped.http import HttpClient, resolve_verify
from untaped.output import OutputFormat, format_output
from untaped.profile_resolver import (
    DEFAULT_PROFILE,
    ProfileSource,
    classify_active_profile,
    effective_active_profile_name,
    resolve_profiles,
)
from untaped.settings import (
    HttpSettings,
    PluginInstallSpec,
    PluginsState,
    Settings,
    get_config_section,
    get_core_settings,
    get_profile_settings_model,
    get_settings,
    get_settings_model,
    register_profile_settings,
    register_state_settings,
    resolve_config_path,
    splice_registered_state,
    validate_settings_isolated,
)
from untaped.stdin import read_identifiers, read_stdin
from untaped.ui import (
    BUILTIN_THEMES,
    ThemeSpec,
    UiContext,
    UiSettings,
    resolve_theme,
    ui_context,
)

__all__ = [
    "BUILTIN_THEMES",
    "DEFAULT_PROFILE",
    "ColumnsOption",
    "ConfigError",
    "FieldDescriptor",
    "FormatOption",
    "HttpClient",
    "HttpError",
    "HttpSettings",
    "OutputFormat",
    "PluginInstallSpec",
    "PluginsState",
    "ProfileOverrideOption",
    "ProfileSource",
    "Settings",
    "ThemeSpec",
    "UiContext",
    "UiSettings",
    "UntapedError",
    "clamp_parallel",
    "classify_active_profile",
    "effective_active_profile_name",
    "find_descriptor",
    "first_validation_error",
    "format_output",
    "get_config_section",
    "get_core_settings",
    "get_profile_settings_model",
    "get_settings",
    "get_settings_model",
    "parse_kv_pairs",
    "profile_override",
    "read_identifiers",
    "read_stdin",
    "redact_secrets",
    "register_profile_settings",
    "register_state_settings",
    "report_errors",
    "resolve_config_path",
    "resolve_each",
    "resolve_profiles",
    "resolve_theme",
    "resolve_verify",
    "secret_field_paths",
    "splice_registered_state",
    "ui_context",
    "validate_settings_isolated",
    "walk_settings",
]
