"""Deprecated alias of :mod:`untaped.capability_api` (kept for one release).

``untaped.capability_api`` is the single public SDK surface. This module only
re-exports the names it historically published so existing imports keep
working; it emits no warning at import time. Import from
``untaped.capability_api`` instead — this module will be removed.
"""

from __future__ import annotations

from untaped.capability_api import (
    AppContext,
    BatchOutcome,
    ColumnsOption,
    ConfigError,
    FormatOption,
    GitCommandError,
    GitResult,
    HttpClient,
    HttpError,
    HttpSettings,
    HttpStatusError,
    HttpTransportError,
    OutputFormat,
    PipeEnvelope,
    ProgressHandle,
    PromptChoice,
    RetryPolicy,
    StateCollection,
    StateMap,
    UiContext,
    UntapedError,
    app_context,
    atomic_write,
    batch_apply,
    bounded_map,
    clamp_parallel,
    connected_client,
    create_app,
    echo,
    emit,
    existing_file,
    finish,
    first_validation_error,
    get_config_section,
    get_core_settings,
    git_auth_header,
    is_envelope_line,
    paginate_link,
    paginate_offset,
    paginate_pages,
    parse_envelope_line,
    parse_json_pairs,
    parse_kv_pairs,
    raise_usage,
    read_identifiers,
    read_stdin,
    read_structured_file,
    render_rows,
    report_errors,
    resolve_each,
    resolve_text_input,
    resolve_verify,
    run_git,
    safe_cache_path,
    safe_path_segment,
    ui_context,
    unified_diff_text,
)
from untaped.cli import existing_directory
from untaped.config_file import ensure_config, mutate_tool_state, read_tool_state
from untaped.diff import DiffStats, diff_stats
from untaped.fs import FileChange, FileWriteError, apply_file_changes
from untaped.http import missing_setting_error
from untaped.pipe import common_kind
from untaped.settings import get_settings
from untaped.stdin import read_records, read_stdin_text
from untaped.theme import ThemeSpec


def invalidate_settings_cache() -> None:
    """Drop the cached settings instance so the next read re-resolves."""
    get_settings.cache_clear()


__all__ = [
    "AppContext",
    "BatchOutcome",
    "ColumnsOption",
    "ConfigError",
    "DiffStats",
    "FileChange",
    "FileWriteError",
    "FormatOption",
    "GitCommandError",
    "GitResult",
    "HttpClient",
    "HttpError",
    "HttpSettings",
    "HttpStatusError",
    "HttpTransportError",
    "OutputFormat",
    "PipeEnvelope",
    "ProgressHandle",
    "PromptChoice",
    "RetryPolicy",
    "StateCollection",
    "StateMap",
    "ThemeSpec",
    "UiContext",
    "UntapedError",
    "app_context",
    "apply_file_changes",
    "atomic_write",
    "batch_apply",
    "bounded_map",
    "clamp_parallel",
    "common_kind",
    "connected_client",
    "create_app",
    "diff_stats",
    "echo",
    "emit",
    "ensure_config",
    "existing_directory",
    "existing_file",
    "finish",
    "first_validation_error",
    "get_config_section",
    "get_core_settings",
    "get_settings",
    "git_auth_header",
    "invalidate_settings_cache",
    "is_envelope_line",
    "missing_setting_error",
    "mutate_tool_state",
    "paginate_link",
    "paginate_offset",
    "paginate_pages",
    "parse_envelope_line",
    "parse_json_pairs",
    "parse_kv_pairs",
    "raise_usage",
    "read_identifiers",
    "read_records",
    "read_stdin",
    "read_stdin_text",
    "read_structured_file",
    "read_tool_state",
    "render_rows",
    "report_errors",
    "resolve_each",
    "resolve_text_input",
    "resolve_verify",
    "run_git",
    "safe_cache_path",
    "safe_path_segment",
    "ui_context",
    "unified_diff_text",
]
