"""Application-layer protocols (ports) for the config bounded context."""

from __future__ import annotations

from typing import Any, Protocol

from untaped.config_schema import FieldDescriptor
from untaped.settings import Settings


class SettingsReader(Protocol):
    """Read-side surface used by ``ListSettings`` / ``ListAllProfilesSettings``."""

    def descriptor(self, key: str) -> FieldDescriptor: ...
    def descriptors(self) -> list[FieldDescriptor]: ...
    def current_settings(self) -> Settings: ...
    def env_value_for(self, descriptor: FieldDescriptor) -> str | None: ...
    def provenance(self) -> dict[tuple[str, ...], str]: ...
    def profile_data(self, name: str) -> dict[str, Any] | None: ...
    def supports_profiles(self) -> bool: ...
    def profile_names(self) -> list[str]: ...
    def ui_descriptor(self, key: str) -> FieldDescriptor: ...
    def yaml_dict(self) -> dict[str, Any]: ...


class SettingsRepository(SettingsReader, Protocol):
    """Read + write surface used by ``SetSetting`` / ``UnsetSetting``."""

    def set_value(self, key: str, raw_value: str, *, profile: str | None = None) -> str | None: ...
    def unset_value(self, key: str, *, profile: str | None = None) -> tuple[bool, str | None]: ...


__all__ = ["SettingsReader", "SettingsRepository"]
