"""Protocols (ports) for the root config command group."""

from __future__ import annotations

from typing import Any, Protocol

from pydantic import BaseModel

from untaped.config_schema import FieldDescriptor
from untaped.stability import Stability


class SettingsReader(Protocol):
    """Read-side surface used by config listing, get, and prompt-default flows."""

    def descriptor(self, key: str) -> FieldDescriptor: ...
    def descriptors(self) -> list[FieldDescriptor]: ...
    def setting_value(self, descriptor: FieldDescriptor) -> Any: ...
    def raw_setting_value(self, descriptor: FieldDescriptor) -> Any: ...
    def env_value_for(self, descriptor: FieldDescriptor) -> str | None: ...
    def deprecated_source(self, descriptor: FieldDescriptor) -> str | None: ...
    def mark(self, descriptor: FieldDescriptor) -> Stability | None: ...
    def section_model(self, section: str) -> type[BaseModel] | None: ...
    def provenance(self) -> dict[tuple[str, ...], str]: ...
    def profile_data(self, name: str) -> dict[str, Any] | None: ...
    def profile_names(self) -> list[str]: ...


__all__ = ["SettingsReader"]
