"""Cyclopts commands for the AWX / AAP domain.

Top-level commands (``ping``, ``apply``, ``save``, ``jobs``) live here.
Per-resource sub-apps (``job-templates``, ``projects``, …) are
generated by :func:`make_resource_app` and attached at module load.
"""

from __future__ import annotations

import json
import re
from collections.abc import Iterable
from pathlib import Path
from typing import Annotated

from cyclopts import Parameter

from untaped.capabilities.awx.application import Ping, TailJobLogs, WatchJob
from untaped.capabilities.awx.cli._apply_runner import run_apply
from untaped.capabilities.awx.cli._mutation_runner import validate_controls
from untaped.capabilities.awx.cli.context import open_context
from untaped.capabilities.awx.cli.event_render import render_event_text
from untaped.capabilities.awx.cli.factory import make_resource_app
from untaped.capabilities.awx.cli.job_actions import register_job_actions
from untaped.capabilities.awx.cli.job_targets import JOB_KIND_HELP as _JOB_KIND_HELP
from untaped.capabilities.awx.cli.job_targets import JobIdsArgument, JobKind
from untaped.capabilities.awx.cli.job_targets import as_job_id as _as_job_id
from untaped.capabilities.awx.cli.job_targets import job_targets as _job_targets
from untaped.capabilities.awx.cli.options import (
    ContinueOption,
    DryRunOption,
    OrganizationOption,
    ParallelOption,
    UnverifiedOption,
    YesOption,
)
from untaped.capabilities.awx.cli.save_runner import run_save_batch
from untaped.capabilities.awx.cli.suite_commands import app as test_app
from untaped.capabilities.awx.cli.unified_templates_commands import app as unified_templates_app
from untaped.capabilities.awx.cli.usage_commands import register_usage_command
from untaped.capabilities.awx.cli.workflow_node_commands import register_nodes_command
from untaped.capabilities.awx.domain import Job, JobEvent
from untaped.capabilities.awx.domain.job import JOB_ROUTES
from untaped.capabilities.awx.infrastructure.specs import ALL_SPECS
from untaped.capability_api import (
    ColumnsOption,
    FormatOption,
    OutputFormat,
    UiContext,
    create_app,
    deprecated_alias,
    echo,
    emit,
    finish,
    parse_kv_pairs,
    raise_usage,
    render_rows,
    report_errors,
    resolve_each,
)

app = create_app(
    name="awx",
    help="Talk to Ansible Automation Platform / AWX.",
)


# ---- ping ----


@app.command(name="ping")
def ping_command(
    *,
    fmt: FormatOption = "table",
    columns: ColumnsOption = None,
) -> None:
    """Check control-plane health."""
    with report_errors():
        with open_context() as ctx:
            status = Ping(ctx.client)()
        emit(status, fmt=fmt, columns=columns, kind="awx.status")


# ---- top-level apply (multi-kind, file or directory) ----


@app.command(name="apply")
def apply_command(
    file: Annotated[Path, Parameter(help="YAML file or directory.")],
    /,
    *,
    yes: YesOption = False,
    dry_run: DryRunOption = False,
    continue_on_error: ContinueOption = False,
    parallel: ParallelOption = 1,
    allow_unverified: UnverifiedOption = False,
    fmt: FormatOption = "table",
    columns: ColumnsOption = None,
) -> None:
    """Create/update YAML documents in dependency order, with one confirmation."""
    with report_errors():
        parallel = validate_controls(
            yes=yes, dry_run=dry_run, allow_unverified=allow_unverified, parallel=parallel
        )
        with open_context() as ctx:
            run_apply(
                ctx,
                file,
                yes=yes,
                dry_run=dry_run,
                continue_on_error=continue_on_error,
                parallel=parallel,
                allow_unverified=allow_unverified,
                fmt=fmt,
                columns=columns,
            )


# ---- top-level save ----


def _reject_duplicate_org_scope(
    organization: str | None,
    filters: dict[str, str],
) -> None:
    if organization is None:
        return
    for key in filters:
        if _is_raw_org_scope_filter(key):
            raise_usage(
                f"do not combine --org/--organization with --filter {key}=...; "
                "use --org for organization-scoped bulk save"
            )


def _is_raw_org_scope_filter(key: str) -> bool:
    return (
        key == "organization"
        or key.startswith("organization__")
        or (key == "inventory__organization" or key.startswith("inventory__organization__"))
    )


@app.command(name="export")
def export_top_command(
    *,
    out_dir: Annotated[
        Path,
        Parameter(name="--out-dir", help="Directory to write per-resource files into."),
    ],
    all_kinds: Annotated[
        bool,
        Parameter(
            name="--all-kinds",
            negative="",
            help="Export every exportable kind (iterate the type axis).",
        ),
    ] = False,
    kind: Annotated[
        str | None,
        Parameter(
            name="--kind",
            help=(
                "Limit the export to a single kind. Accepts a CLI name "
                "(job-templates) or a domain kind (JobTemplate)."
            ),
        ),
    ] = None,
    organization: OrganizationOption = None,
    filter_: Annotated[
        list[str] | None,
        Parameter(
            name="--filter",
            help=(
                "Expert server-side filter, KEY=VALUE (repeatable). Passed "
                "verbatim to AWX for each exported kind. For organization backups, "
                "prefer --org so each kind gets a compatible scope."
            ),
            consume_multiple=False,
            negative="",
        ),
    ] = None,
    print_paths: Annotated[
        bool,
        Parameter(
            name="--print-paths",
            negative="",
            help="Emit written filenames on stdout instead of the YAML envelopes for scripts.",
        ),
    ] = False,
) -> None:
    """Bulk-export resources to a directory.

    ``export --all-kinds --out-dir DIR`` writes one file per resource
    using the full identity in the filename so same-named records
    across organizations don't collide:
    ``<Kind>[__<org>][__<parent_kind>__[<parent_org>__]<parent_name>]__<name>.yml``.
    Kinds with read-only fidelity (Credential) are skipped with a
    one-line note.

    Default stdout shape is a multi-doc YAML stream of the same
    envelopes the files contain, so the dump pipes straight into
    ``apply`` (``---``-separated docs, one per record). Pass
    ``--print-paths`` to swap stdout for the written-file list
    instead.
    """
    if not all_kinds and not kind:
        raise_usage("pass --all-kinds or --kind")
    filters = parse_kv_pairs(filter_, flag="--filter")
    _reject_duplicate_org_scope(organization, filters)

    with report_errors(), open_context() as ctx:
        run_save_batch(
            ctx,
            out_dir=out_dir,
            all_kinds=all_kinds,
            kind=kind,
            filters=filters,
            organization=organization,
            print_paths=print_paths,
        )


# ---- jobs (execution records) ----


jobs_app = create_app(name="jobs", help="Inspect, cancel and relaunch AWX jobs.")


@jobs_app.command(name="list")
def jobs_list(
    *,
    status: Annotated[
        str | None,
        Parameter(name="--status", help="Filter by AWX status (e.g. running, successful, failed)."),
    ] = None,
    filter_: Annotated[
        list[str] | None,
        Parameter(
            name="--filter",
            help="Server-side filter, KEY=VALUE (repeatable). Forwarded verbatim.",
            consume_multiple=False,
            negative="",
        ),
    ] = None,
    limit: Annotated[
        int,
        Parameter(name="--limit", help="Newest N jobs (default 20; 0 lists every job)."),
    ] = 20,
    kind: Annotated[JobKind, Parameter(name="--kind", help=_JOB_KIND_HELP)] = "job",
    template: Annotated[
        str | None,
        Parameter(
            name="--template",
            help=(
                "Only runs of this template (project or inventory source for updates): "
                "a name, or digits for an AWX id."
            ),
        ),
    ] = None,
    fmt: FormatOption = "table",
    columns: ColumnsOption = None,
) -> None:
    """List recent AWX jobs (newest first)."""
    if limit < 0:
        raise_usage("--limit must be non-negative")
    filters = parse_kv_pairs(filter_, flag="--filter")
    if status:
        filters["status"] = status
    if template is not None:
        field = JOB_ROUTES[kind].template_field
        if field is None:
            raise_usage(f"--template does not apply to {kind} executions")
        filters[field if template.isdigit() else f"{field}__name"] = template
    with report_errors(), open_context() as ctx, ctx.progress_ui().progress("Loading jobs…"):
        records = list(ctx.jobs.list(kind=kind, params=filters, limit=limit or None))
    cols = list(columns) if columns else ["id", "name", "status"]
    rendered = render_rows(
        records,
        fmt=fmt,
        columns=cols,
        kind="awx.job",
        empty="No jobs found. Try a different --status or --filter.",
    )
    if rendered:
        echo(rendered)


@jobs_app.command(name="get")
def jobs_get(
    job_ids: JobIdsArgument = None,
    /,
    *,
    stdin: Annotated[
        bool,
        Parameter(name="--stdin", negative="", help="Read job ids from stdin (one per line)."),
    ] = False,
    kind: Annotated[JobKind, Parameter(name="--kind", help=_JOB_KIND_HELP)] = "job",
    fmt: FormatOption = "table",
    columns: ColumnsOption = None,
) -> None:
    """Fetch one or more jobs by id."""
    # Hoisted so they're bound even if ``report_errors`` swallows the
    # body — keeps the post-``with`` exit-code dispatch safe.
    records: list[dict[str, object]] = []
    any_failed = False
    with report_errors(), open_context() as ctx:
        ids, kinds = _job_targets(job_ids, stdin=stdin, kind=kind)
        records, any_failed = resolve_each(
            ids, lambda n: ctx.jobs.get(kind=kinds.get(n, kind), job_id=_as_job_id(n))
        )
    if records:
        emit(records, fmt=fmt, columns=list(columns) if columns else [], kind="awx.job")
    finish(any_failed)


@jobs_app.command(name="events")
def jobs_events(
    job_ids: JobIdsArgument = None,
    /,
    *,
    stdin: Annotated[
        bool,
        Parameter(name="--stdin", negative="", help="Read job ids from stdin (one per line)."),
    ] = False,
    follow: Annotated[
        bool,
        Parameter(name="--follow", negative="", help="Tail events live until terminal."),
    ] = False,
    from_counter: Annotated[
        int,
        Parameter(name="--from-counter", help="Skip events with counter <= this value."),
    ] = 0,
    filter_: Annotated[
        list[str] | None,
        Parameter(
            name="--filter",
            help="Server-side AWX filter, KEY=VALUE (repeatable). E.g. event=runner_on_failed.",
            consume_multiple=False,
            negative="",
        ),
    ] = None,
    kind: Annotated[JobKind, Parameter(name="--kind", help=_JOB_KIND_HELP)] = "job",
    fmt: FormatOption = "table",
    columns: ColumnsOption = None,
) -> None:
    """Stream the structured per-task event log for one or more jobs.

    Without ``--follow`` this drains each job's event log and exits;
    with ``--follow`` it polls AWX every 2s until each job is terminal.
    Filters reach AWX directly so you can scope server-side, e.g.
    ``--filter event=runner_on_failed --filter host=web-01``.

    Multiple ids drain serially with a ``[<id>]`` stderr breadcrumb
    between jobs. Without ``--follow``, ``--format json``/``yaml`` print one
    array holding every job's events; each row names its ``job``. With
    ``--follow``, json streams one object per line (NDJSON).
    """
    filters = parse_kv_pairs(filter_, flag="--filter")
    cols = list(columns) if columns else _event_columns(fmt)
    one_document = _is_one_document(fmt, follow=follow)
    rows: list[dict[str, object]] = []
    # Hoisted so post-``with`` exit dispatch is safe regardless of body outcome.
    any_failed = False
    with report_errors(), open_context() as ctx:
        ids, kinds = _job_targets(job_ids, stdin=stdin, kind=kind)
        show_breadcrumb = len(ids) > 1

        def _events_for_id(n: str) -> None:
            job_id = _as_job_id(n)
            job_kind = kinds.get(n, kind)
            record = ctx.jobs.get(kind=job_kind, job_id=job_id)
            job = Job.model_validate({**record, "kind": job_kind})
            if show_breadcrumb:
                echo(f"[{job_id}]", err=True)
            events = ctx.monitor.stream_events(
                job, from_counter=from_counter, params=filters, follow=follow
            )
            if one_document:
                rows.extend(_event_row(ev, job_id) for ev in events)
                return
            _emit_events(
                events, job_id=job_id, fmt=fmt, cols=cols, follow=follow, ui=ctx.progress_ui()
            )

        drained, any_failed = resolve_each(ids, _events_for_id)
        if one_document and drained:
            echo(render_rows(rows, fmt=fmt, columns=cols, kind="awx.event"))
    finish(any_failed)


def _is_one_document(fmt: OutputFormat, *, follow: bool) -> bool:
    """Whether several jobs' rows merge into one json/yaml document.

    json and yaml print a single document per invocation; ``--follow``
    streams instead (json as NDJSON), and the other formats are line or
    table oriented, so they keep emitting per job.
    """
    return not follow and fmt in ("json", "yaml")


def _event_columns(fmt: OutputFormat) -> list[str]:
    """Default ``jobs events`` columns; structured formats lead with ``job``."""
    base = ["counter", "event", "host_name", "task"]
    return base if fmt in ("table", "raw") else ["job", *base]


def _event_row(ev: JobEvent, job_id: int) -> dict[str, object]:
    return {"job": job_id, **ev.model_dump()}


def _emit_events(
    events: Iterable[JobEvent],
    *,
    job_id: int,
    fmt: OutputFormat,
    cols: list[str],
    follow: bool,
    ui: UiContext,
) -> None:
    """Lifted out of the per-id closure so multi-id callers reuse
    the single-id rendering verbatim — no behavioural drift between
    batch and single modes."""
    if not follow:
        # One-shot drain: collect everything then format as a single
        # table / json document so columns line up and yaml stays a
        # well-formed list.
        rows = [_event_row(ev, job_id) for ev in events]
        echo(render_rows(rows, fmt=fmt, columns=cols, kind="awx.event"))
        return
    if fmt == "table":
        # Table mode under --follow renders each event as a colored
        # human-readable line (PLAY [..] / TASK [..] / "  ok: host"),
        # similar to the AWX UI's Output tab. ``ui.styled`` emits ANSI
        # on a real terminal and plain text when piped or redirected.
        for ev in events:
            ui.styled(render_event_text(ev))
        return
    # Other formats (json/yaml/raw) stream one structured row at a
    # time — useful for ``--follow | jq``-style pipelines.
    # JSON streams as NDJSON (one bare object per line, no enclosing
    # array brackets) to match ``kubectl get -w -o json`` and so
    # ``jq`` can ingest it directly without ``jq -s '.[]'``.
    if fmt == "json":
        for ev in events:
            full = _event_row(ev, job_id)
            echo(json.dumps({c: full.get(c) for c in cols}, default=str))
        return
    for ev in events:
        line = render_rows([_event_row(ev, job_id)], fmt=fmt, columns=cols, kind="awx.event")
        echo(line)


def _emit_log_lines(
    lines: Iterable[str],
    *,
    job_id: int,
    fmt: OutputFormat,
    cols: list[str] | None,
    follow: bool,
) -> None:
    """Render the stdout of a job. Sibling of :func:`_emit_events`.

    ``cols=None`` (vs ``_emit_events``'s required ``list[str]``) means
    "emit every field of the row" — logs has no default columns whereas
    events has ``["counter","event","host_name","task"]``.
    """
    if not follow:
        rendered = render_rows(
            [_log_row(line, job_id) for line in lines], fmt=fmt, columns=cols, kind="awx.log"
        )
        if rendered:
            echo(rendered)
        return
    # JSON streams as NDJSON (one bare object per line, no enclosing
    # array brackets) to match ``jobs events --follow --format json``
    # and so ``jq`` can ingest it directly without ``jq -s '.[]'``.
    if fmt == "json":
        for line in lines:
            row = _log_row(line, job_id)
            if cols is not None:
                row = {c: row.get(c) for c in cols}
            echo(json.dumps(row, default=str))
        return
    if fmt == "raw":
        # Skip the no-op row-rendering round-trip — raw lines are
        # already the final shape, and the per-line wrap is the hot path
        # on a 100k-line follow stream. ``cols`` is ignored here: log
        # rows are single-field (``line``), so any projection is either
        # the identity or a path miss; the only meaningful value is
        # ``--columns line``, which is what users pass.
        for line in lines:
            echo(line)
        return
    # No Rich table branch (unlike ``_emit_events``): log lines are
    # unstructured text, so ``--format table --follow`` falls through
    # to per-line row rendering like yaml does. Table-per-line is
    # silly but the cost is on the user who asked for it.
    for line in lines:
        echo(render_rows([_log_row(line, job_id)], fmt=fmt, columns=cols, kind="awx.log"))


def _log_row(line: str, job_id: int) -> dict[str, object]:
    return {"job": job_id, "line": line}


@jobs_app.command(name="logs")
def jobs_logs(
    job_ids: JobIdsArgument = None,
    /,
    *,
    stdin: Annotated[
        bool,
        Parameter(name="--stdin", negative="", help="Read job ids from stdin (one per line)."),
    ] = False,
    follow: Annotated[
        bool,
        Parameter(name="--follow", negative="", help="Tail until terminal."),
    ] = False,
    tail: Annotated[
        int | None,
        Parameter(name="--tail", help="Show only the last N historical lines before following."),
    ] = None,
    grep: Annotated[
        str | None,
        Parameter(name="--grep", help="Client-side regex; only matching lines are printed."),
    ] = None,
    ignore_case: Annotated[
        bool,
        Parameter(name=["--ignore-case", "-i"], negative="", help="Case-insensitive --grep."),
    ] = False,
    kind: Annotated[JobKind, Parameter(name="--kind", help=_JOB_KIND_HELP)] = "job",
    fmt: Annotated[
        OutputFormat,
        Parameter(name="--format", help="Output format."),
    ] = "raw",
    columns: ColumnsOption = None,
) -> None:
    """Print the stdout of one or more jobs. Supports follow / tail / grep.

    Multiple ids drain serially with a ``[<id>]`` stderr breadcrumb
    between jobs. Without ``--follow``, ``--format json``/``yaml`` print one
    array holding every job's lines; each row names its ``job``.
    """
    if grep is not None:
        # Compile here so an invalid regex fails fast as a clean
        # usage error rather than
        # leaking a ``re.error`` traceback through ``report_errors`` later.
        try:
            re.compile(grep, re.IGNORECASE if ignore_case else 0)
        except re.error as exc:
            raise_usage(f"--grep {grep!r} is not a valid regex: {exc}")
    # Hoisted so post-``with`` exit dispatch is safe regardless of body outcome.
    any_failed = False
    with report_errors(), open_context() as ctx:
        ids, kinds = _job_targets(job_ids, stdin=stdin, kind=kind)
        show_breadcrumb = len(ids) > 1
        # Log rows are ``{job, line}``; the line-oriented formats show the line.
        cols = list(columns) if columns else (["line"] if fmt in ("table", "raw") else None)
        one_document = _is_one_document(fmt, follow=follow)
        rows: list[dict[str, object]] = []

        def _logs_for_id(n: str) -> None:
            job_id = _as_job_id(n)
            job_kind = kinds.get(n, kind)
            record = ctx.jobs.get(kind=job_kind, job_id=job_id)
            job = Job.model_validate({**record, "kind": job_kind})
            if show_breadcrumb:
                echo(f"[{job_id}]", err=True)
            lines = TailJobLogs(ctx.monitor)(
                job, follow=follow, grep=grep, ignore_case=ignore_case, tail=tail
            )
            if one_document:
                rows.extend(_log_row(line, job_id) for line in lines)
                return
            _emit_log_lines(lines, job_id=job_id, fmt=fmt, cols=cols, follow=follow)

        drained, any_failed = resolve_each(ids, _logs_for_id)
        if one_document and drained:
            echo(render_rows(rows, fmt=fmt, columns=cols, kind="awx.log"))
    finish(any_failed)


@jobs_app.command(name="wait")
def jobs_wait(
    job_ids: JobIdsArgument = None,
    /,
    *,
    stdin: Annotated[
        bool,
        Parameter(name="--stdin", negative="", help="Read job ids from stdin (one per line)."),
    ] = False,
    timeout: Annotated[
        float | None,
        Parameter(name="--timeout", help="Seconds to wait before giving up (applies per id)."),
    ] = None,
    kind: Annotated[JobKind, Parameter(name="--kind", help=_JOB_KIND_HELP)] = "job",
    fmt: FormatOption = "table",
    columns: ColumnsOption = None,
) -> None:
    """Block until each named job reaches a terminal state.

    Exits non-zero on unsuccessful terminal states, timeout, or resolution failure —
    same contract as ``awx test``. Multiple ids drain serially; the
    ``--timeout`` budget applies per id.
    """
    # Hoisted so post-``with`` exit dispatch is safe regardless of body outcome.
    records: list[dict[str, object]] = []
    any_failed = False
    timed_out: list[int] = []
    with report_errors(), open_context() as ctx:
        ids, kinds = _job_targets(job_ids, stdin=stdin, kind=kind)

        def _wait_one(n: str) -> dict[str, object]:
            job_id = _as_job_id(n)
            job_kind = kinds.get(n, kind)
            record = ctx.jobs.get(kind=job_kind, job_id=job_id)
            job = Job.model_validate({**record, "kind": job_kind})
            final = WatchJob(ctx.repo)(job, timeout=timeout)
            if not final.is_terminal:
                timed_out.append(job_id)
            return final.model_dump()

        records, any_failed = resolve_each(ids, _wait_one)
    if records:
        emit(records, fmt=fmt, columns=columns, kind="awx.job")
    for job_id in timed_out:
        echo(f"timeout: job {job_id} did not reach terminal state", err=True)
    finish(any_failed or bool(timed_out) or any(r["status"] != "successful" for r in records))


register_job_actions(jobs_app)
app.command(jobs_app, name="jobs")
deprecated_alias(app, "save", "export")
deprecated_alias(jobs_app["logs"], "-f", "--follow")
app.command(unified_templates_app, name="unified-templates")
app.command(test_app, name="test")


# ---- per-resource sub-apps (factory-generated) ----


for spec in ALL_SPECS:
    if not spec.commands:
        # Catalog-only stubs (e.g. ExecutionEnvironment, Label) exist purely
        # so :class:`FkResolver` can resolve names → ids for launch-payload
        # FKs. They have no user-facing CLI surface.
        continue
    sub_app = make_resource_app(spec)
    if spec.kind == "WorkflowJobTemplate":
        register_nodes_command(sub_app)
    if spec.kind in {"JobTemplate", "WorkflowJobTemplate"}:
        register_usage_command(sub_app, spec)
    app.command(sub_app, name=spec.cli_name)
