"""Typer commands for the AWX / AAP domain.

Top-level commands (``ping``, ``apply``, ``save``, ``jobs``) live here.
Per-resource sub-apps (``job-templates``, ``projects``, …) are
generated by :func:`make_resource_app` and attached at module load.
"""

from __future__ import annotations

import json
import re
from pathlib import Path

import typer
from rich.console import Console
from untaped_core import (
    ColumnsOption,
    FormatOption,
    OutputFormat,
    format_output,
    get_settings,
    parse_kv_pairs,
    report_errors,
)

from untaped_awx.application import (
    Ping,
    SaveResource,
    StreamJobEvents,
    TailJobLogs,
    WatchJob,
)
from untaped_awx.cli._apply_runner import run_apply
from untaped_awx.cli._context import awx_config_from_settings, open_context
from untaped_awx.cli._event_render import render_event_text
from untaped_awx.cli.resource_commands import make_resource_app
from untaped_awx.cli.test_commands import app as test_app
from untaped_awx.cli.unified_templates_commands import app as unified_templates_app
from untaped_awx.domain import Job, Metadata
from untaped_awx.domain.job import KIND_TO_API_PATH
from untaped_awx.errors import AwxApiError
from untaped_awx.infrastructure import AwxClient
from untaped_awx.infrastructure.catalog import AwxResourceCatalog
from untaped_awx.infrastructure.spec import AwxResourceSpec
from untaped_awx.infrastructure.specs import ALL_SPECS
from untaped_awx.infrastructure.yaml_io import write_resource

app = typer.Typer(
    name="awx",
    help="Talk to Ansible Automation Platform / AWX.",
    no_args_is_help=True,
)


@app.callback()
def _callback() -> None:
    """Talk to Ansible Automation Platform / AWX."""


# ---- ping ----


@app.command("ping")
def ping_command(
    fmt: FormatOption = "table",
    columns: ColumnsOption = None,
) -> None:
    """Check control-plane health."""
    with report_errors():
        settings = get_settings()
        config = awx_config_from_settings(settings)
        with AwxClient(config, http=settings.http) as client:
            status = Ping(client)()
        typer.echo(format_output([status.model_dump()], fmt=fmt, columns=columns))


# ---- top-level apply (multi-kind, file or directory) ----


@app.command("apply", no_args_is_help=True)
def apply_command(
    file: Path = typer.Option(..., "--file", help="YAML file or directory."),
    yes: bool = typer.Option(False, "--yes", help="Actually write (default is preview only)."),
    fail_fast: bool = typer.Option(False, "--fail-fast", help="Abort on first error."),
    fmt: OutputFormat = typer.Option("table", "--format", "-f", help="Result-table format."),
    columns: list[str] | None = typer.Option(None, "--columns", "-c"),
) -> None:
    """Apply YAML docs in dependency order. Default = preview; ``--yes`` writes."""
    with report_errors(), open_context() as ctx:
        run_apply(
            ctx,
            file,
            write=yes,
            fail_fast=fail_fast,
            fmt=fmt,
            columns=columns,
        )


# ---- top-level save (--all bulk dump) ----


@app.command("save", no_args_is_help=True)
def save_top_command(
    out_dir: Path = typer.Option(
        ..., "--out-dir", help="Directory to write per-resource files into."
    ),
    all_kinds: bool = typer.Option(False, "--all", help="Save every saveable kind."),
    kind: str | None = typer.Option(
        None,
        "--kind",
        help=(
            "Limit save to a single kind. Accepts a CLI name "
            "(job-templates) or a domain kind (JobTemplate)."
        ),
    ),
    filter_: list[str] | None = typer.Option(
        None,
        "--filter",
        help=(
            "Server-side filter, KEY=VALUE (repeatable). Passed verbatim to "
            "AWX for each saved kind. Note: AWX's /schedules/ endpoint has "
            "no organization field, so filters like organization__name=… "
            "are 400'd by that endpoint — do a separate per-kind save if "
            "you need org-scoped schedules."
        ),
    ),
) -> None:
    """Bulk-save resources to a directory.

    ``save --all --out-dir DIR`` writes one file per resource using the
    full identity in the filename so same-named records across
    organizations don't collide:
    ``<Kind>[__<org>][__<parent_kind>__[<parent_org>__]<parent_name>]__<name>.yml``.
    Kinds with read-only fidelity (Credential) are skipped with a
    one-line note.
    """
    if not all_kinds and not kind:
        raise typer.BadParameter("pass --all or --kind")
    filters = parse_kv_pairs(filter_, flag="--filter")

    with report_errors(), open_context() as ctx:
        target_specs = (
            list(ALL_SPECS) if all_kinds else [_resolve_kind(ctx.catalog, kind)]  # type: ignore[arg-type]
        )
        save = SaveResource(ctx.repo, ctx.fk)
        out_dir.mkdir(parents=True, exist_ok=True)
        written: list[str] = []
        for spec in target_specs:
            if spec.fidelity == "read_only":
                typer.echo(
                    f"skipping {spec.kind}: not roundtrippable in v0",
                    err=True,
                )
                continue
            if "save" not in spec.commands:
                continue
            incompatible = _filter_field_not_on_spec(filters, spec)
            if incompatible is not None:
                typer.echo(
                    f"skipping {spec.kind}: filter field {incompatible!r} not on this kind",
                    err=True,
                )
                continue
            records = save.find_all(spec, params=filters or None)
            for record in records:
                resource = save.from_record(spec, record)
                comment = spec.fidelity_note if spec.fidelity != "full" else None
                target = out_dir / _resource_filename(spec.kind, resource.metadata)
                _assert_inside(out_dir, target)
                write_resource(target, resource, header_comment=comment)
                written.append(str(target))
    for path in written:
        typer.echo(path)


def _resolve_kind(catalog: AwxResourceCatalog, kind: str) -> AwxResourceSpec:
    """Accept either the public CLI name (``job-templates``) or the
    domain kind (``JobTemplate``)."""
    try:
        return catalog.by_cli_name(kind)
    except AwxApiError:
        return catalog.get(kind)


def _filter_field_not_on_spec(filters: dict[str, str], spec: AwxResourceSpec) -> str | None:
    """Return a filter field that doesn't exist on ``spec``, or None.

    AWX's ``/schedules/`` has no ``organization`` field — sending
    ``?organization__name=…`` 400s. This is a *conservative* heuristic
    to skip kinds whose API can't possibly accept a given filter key,
    union'ing every field name we know each kind exposes:

    - ``canonical_fields`` (writable input fields)
    - ``identity_keys`` (always queryable)
    - ``read_only_fields`` (server-set; ``modified``, ``status``, …)
    - ``fk_refs.field`` (FK columns)
    - ``list_columns`` (we wouldn't display a column that doesn't exist)

    AWX exposes more filterable fields than any spec enumerates, so a
    false positive is possible — kinds whose specs lag the API will be
    spuriously skipped on otherwise-valid filters. The recovery is
    either to add the missing field to the spec or to run a per-kind
    save without the filter. False *negatives* (sending an invalid
    filter that AWX 400s on) are caught by the per-call error path.
    """
    fields = (
        set(spec.canonical_fields)
        | set(spec.identity_keys)
        | set(spec.read_only_fields)
        | set(spec.list_columns)
        | {fk.field for fk in spec.fk_refs}
    )
    for key in filters:
        base = key.split("__", 1)[0]
        if base not in fields:
            return base
    return None


_UNSAFE_FILENAME_CHARS = re.compile(r"[/\\\x00-\x1f]")


def _safe_filename_segment(name: str) -> str:
    """Return a filesystem-safe segment derived from an AWX resource name.

    Replaces path separators and ASCII control chars with ``_``, collapses
    leading/trailing dots so we can never produce ``..`` or ``.``, and falls
    back to ``unnamed`` for empty results. The original name remains in the
    saved YAML's metadata.
    """
    if not name:
        return "unnamed"
    cleaned = _UNSAFE_FILENAME_CHARS.sub("_", name).strip(". ")
    return cleaned or "unnamed"


def _assert_inside(parent: Path, target: Path) -> None:
    """Refuse paths that resolve outside the intended parent directory."""
    parent_resolved = parent.resolve()
    try:
        target.resolve().relative_to(parent_resolved)
    except ValueError as exc:  # pragma: no cover — defensive guard
        raise AwxApiError(f"refusing to write {target} — outside {parent_resolved}") from exc


def _resource_filename(kind: str, metadata: Metadata) -> str:
    """Encode the identity tuple in the filename so same-named records don't collide."""
    parts: list[str] = [kind]
    if metadata.parent is not None:
        parts.append(metadata.parent.kind)
        if metadata.parent.organization:
            parts.append(metadata.parent.organization)
        parts.append(metadata.parent.name)
    elif metadata.organization is not None:
        parts.append(metadata.organization)
    parts.append(metadata.name)
    return "__".join(_safe_filename_segment(p) for p in parts) + ".yml"


# ---- jobs (read-only execution records) ----


jobs_app = typer.Typer(name="jobs", help="Inspect AWX jobs.", no_args_is_help=True)


@jobs_app.callback()
def _jobs_callback() -> None:
    """Inspect AWX jobs."""


_JOB_KIND_HELP = (
    "Execution kind. Defaults to 'job' (a JobTemplate run). Other values: "
    "workflow_job, project_update, inventory_update, ad_hoc_command. "
    "Hits the matching AWX collection (e.g. workflow_jobs/<id>/)."
)


def _kind_path(kind: str) -> str:
    """Return the AWX collection name for ``kind`` (with ``s`` fallback)."""
    return KIND_TO_API_PATH.get(kind, kind)


@jobs_app.command("list")
def jobs_list(
    status: str | None = typer.Option(
        None,
        "--status",
        help="Filter by AWX status (e.g. running, successful, failed).",
    ),
    filter_: list[str] | None = typer.Option(
        None,
        "--filter",
        help="Server-side filter, KEY=VALUE (repeatable). Forwarded verbatim.",
    ),
    limit: int | None = typer.Option(None, "--limit", help="Cap result count."),
    kind: str = typer.Option("job", "--kind", help=_JOB_KIND_HELP),
    fmt: OutputFormat = typer.Option("table", "--format", "-f", help="Output format."),
    columns: ColumnsOption = None,
) -> None:
    """List recent AWX jobs (newest first)."""
    filters = parse_kv_pairs(filter_, flag="--filter")
    if status:
        filters["status"] = status
    # AWX defaults to id-asc; flip so the most recent jobs lead.
    filters.setdefault("order_by", "-id")
    with report_errors(), open_context() as ctx:
        records = list(ctx.repo.paginate_path(f"{_kind_path(kind)}/", params=filters, limit=limit))
    cols = list(columns) if columns else ["id", "name", "status"]
    typer.echo(format_output(records, fmt=fmt, columns=cols))


@jobs_app.command("get", no_args_is_help=True)
def jobs_get(
    job_id: int = typer.Argument(..., help="Job ID."),
    kind: str = typer.Option("job", "--kind", help=_JOB_KIND_HELP),
    fmt: OutputFormat = typer.Option("yaml", "--format", "-f"),
    columns: ColumnsOption = None,
) -> None:
    """Fetch a single job by id."""
    with report_errors(), open_context() as ctx:
        record = ctx.repo.request("GET", f"{_kind_path(kind)}/{job_id}/")
    typer.echo(format_output([record], fmt=fmt, columns=list(columns) if columns else []))


@jobs_app.command("events", no_args_is_help=True)
def jobs_events(
    job_id: int = typer.Argument(..., help="Job ID."),
    follow: bool = typer.Option(False, "--follow", help="Tail events live until terminal."),
    from_counter: int = typer.Option(
        0, "--from-counter", help="Skip events with counter <= this value."
    ),
    filter_: list[str] | None = typer.Option(
        None,
        "--filter",
        help="Server-side AWX filter, KEY=VALUE (repeatable). E.g. event=runner_on_failed.",
    ),
    kind: str = typer.Option("job", "--kind", help=_JOB_KIND_HELP),
    fmt: FormatOption = "table",
    columns: ColumnsOption = None,
) -> None:
    """Stream the structured per-task event log for a job.

    Without ``--follow`` this drains the current event log and exits;
    with ``--follow`` it polls AWX every 2s until the job is terminal.
    Filters reach AWX directly so you can scope server-side, e.g.
    ``--filter event=runner_on_failed --filter host=web-01``.
    """
    filters = parse_kv_pairs(filter_, flag="--filter")
    cols = list(columns) if columns else ["counter", "event", "host_name", "task"]
    with report_errors(), open_context() as ctx:
        record = ctx.repo.request("GET", f"{_kind_path(kind)}/{job_id}/")
        job = Job.model_validate({**record, "kind": kind})
        events = StreamJobEvents(ctx.monitor)(
            job, from_counter=from_counter, filters=filters, follow=follow
        )
        if not follow:
            # One-shot drain: collect everything then format as a single
            # table / json document so columns line up and yaml stays a
            # well-formed list.
            rows = [ev.model_dump() for ev in events]
            typer.echo(format_output(rows, fmt=fmt, columns=cols))
            return
        if fmt == "table":
            # Table mode under --follow renders each event as a colored
            # human-readable line (PLAY [..] / TASK [..] / "  ok: host"),
            # similar to the AWX UI's Output tab. ``rich.console.Console``
            # auto-detects TTY: ANSI on a real terminal, plain text when
            # piped or redirected. No new dependency — Rich is already
            # used for table rendering elsewhere.
            console = Console(highlight=False)
            for ev in events:
                console.print(render_event_text(ev))
            return
        # Other formats (json/yaml/raw) stream one structured row at a
        # time — useful for ``--follow | jq``-style pipelines.
        # JSON streams as NDJSON (one bare object per line, no enclosing
        # array brackets) to match ``kubectl get -w -o json`` and so
        # ``jq`` can ingest it directly without ``jq -s '.[]'``.
        if fmt == "json":
            cols_filter = list(cols) if cols else None
            for ev in events:
                row = ev.model_dump()
                if cols_filter is not None:
                    row = {c: row.get(c) for c in cols_filter}
                typer.echo(json.dumps(row, default=str))
            return
        for ev in events:
            line = format_output([ev.model_dump()], fmt=fmt, columns=cols)
            typer.echo(line)


@jobs_app.command("logs", no_args_is_help=True)
def jobs_logs(
    job_id: int = typer.Argument(..., help="Job ID."),
    follow: bool = typer.Option(False, "--follow", "-f", help="Tail until terminal."),
    tail: int | None = typer.Option(
        None, "--tail", help="Show only the last N historical lines before following."
    ),
    grep: str | None = typer.Option(
        None, "--grep", help="Client-side regex; only matching lines are printed."
    ),
    ignore_case: bool = typer.Option(False, "--ignore-case", "-i", help="Case-insensitive --grep."),
    kind: str = typer.Option("job", "--kind", help=_JOB_KIND_HELP),
) -> None:
    """Print the job's stdout. Supports follow / tail / grep."""
    if grep is not None:
        # Compile here so an invalid regex fails fast as a clean
        # ``BadParameter`` (cleanly mapped to exit 2 by Typer) rather than
        # leaking a ``re.error`` traceback through ``report_errors`` later.
        try:
            re.compile(grep, re.IGNORECASE if ignore_case else 0)
        except re.error as exc:
            raise typer.BadParameter(f"--grep {grep!r} is not a valid regex: {exc}") from exc
    with report_errors(), open_context() as ctx:
        record = ctx.repo.request("GET", f"{_kind_path(kind)}/{job_id}/")
        job = Job.model_validate({**record, "kind": kind})
        for line in TailJobLogs(ctx.monitor)(
            job, follow=follow, grep=grep, ignore_case=ignore_case, tail=tail
        ):
            typer.echo(line)


@jobs_app.command("wait", no_args_is_help=True)
def jobs_wait(
    job_id: int = typer.Argument(..., help="Job ID."),
    timeout: float | None = typer.Option(
        None, "--timeout", help="Seconds to wait before giving up."
    ),
    kind: str = typer.Option("job", "--kind", help=_JOB_KIND_HELP),
    fmt: OutputFormat = typer.Option(
        "table", "--format", "-f", help="Output format (json|yaml|table|raw)."
    ),
    columns: ColumnsOption = None,
) -> None:
    """Block until the job reaches a terminal state.

    Exits non-zero when ``--timeout`` is reached without the job
    reaching a terminal state — same contract as ``awx test``.
    """
    with report_errors(), open_context() as ctx:
        record = ctx.repo.request("GET", f"{_kind_path(kind)}/{job_id}/")
        job = Job.model_validate({**record, "kind": kind})
        final = WatchJob(ctx.repo)(job, timeout=timeout)
    typer.echo(format_output([final.model_dump()], fmt=fmt, columns=columns))
    if not final.is_terminal:
        typer.echo(f"timeout: job {job_id} did not reach terminal state", err=True)
        raise typer.Exit(code=1)


app.add_typer(jobs_app, name="jobs")
app.add_typer(unified_templates_app, name="unified-templates")
app.add_typer(test_app, name="test")


# ---- per-resource sub-apps (factory-generated) ----


for spec in ALL_SPECS:
    if not spec.commands:
        # Catalog-only stubs (e.g. ExecutionEnvironment, Label) exist purely
        # so :class:`FkResolver` can resolve names → ids for launch-payload
        # FKs. They have no user-facing CLI surface.
        continue
    sub_app = make_resource_app(spec)
    app.add_typer(sub_app, name=spec.cli_name)
