"""Typer commands for the AWX / AAP domain.

Top-level commands (``ping``, ``apply``, ``save``, ``jobs``) live here.
Per-resource sub-apps (``job-templates``, ``projects``, …) are
generated by :func:`make_resource_app` and attached at module load.
"""

from __future__ import annotations

import re
from pathlib import Path
from typing import Any

import typer
from untaped_core import (
    ColumnsOption,
    FormatOption,
    OutputFormat,
    format_output,
    get_settings,
    report_errors,
)

from untaped_awx.application import (
    Ping,
    SaveResource,
    WatchJob,
)
from untaped_awx.cli._apply_runner import run_apply
from untaped_awx.cli._context import awx_config_from_settings, open_context, scope_for_spec
from untaped_awx.cli.resource_commands import make_resource_app
from untaped_awx.domain import Job, Metadata, ResourceSpec
from untaped_awx.errors import AwxApiError
from untaped_awx.infrastructure import AwxClient
from untaped_awx.infrastructure.specs import ALL_SPECS
from untaped_awx.infrastructure.yaml_io import write_resource

app = typer.Typer(
    name="awx",
    help="Talk to Ansible Automation Platform / AWX.",
    no_args_is_help=True,
)


@app.callback()
def _callback() -> None:
    """Talk to Ansible Automation Platform / AWX."""


# ---- ping ----


@app.command("ping")
def ping_command(
    fmt: FormatOption = "table",
    columns: ColumnsOption = None,
) -> None:
    """Check control-plane health."""
    with report_errors():
        settings = get_settings()
        config = awx_config_from_settings(settings)
        with AwxClient(config, http=settings.http) as client:
            status = Ping(client)()
        typer.echo(format_output([status.model_dump()], fmt=fmt, columns=columns))


# ---- top-level apply (multi-kind, file or directory) ----


@app.command("apply", no_args_is_help=True)
def apply_command(
    file: Path = typer.Option(..., "--file", help="YAML file or directory."),
    yes: bool = typer.Option(False, "--yes", help="Actually write (default is preview only)."),
    fail_fast: bool = typer.Option(False, "--fail-fast", help="Abort on first error."),
    fmt: OutputFormat = typer.Option("table", "--format", "-f", help="Result-table format."),
    columns: list[str] | None = typer.Option(None, "--columns", "-c"),
) -> None:
    """Apply YAML docs in dependency order. Default = preview; ``--yes`` writes."""
    with report_errors(), open_context() as ctx:
        run_apply(
            ctx,
            file,
            write=yes,
            fail_fast=fail_fast,
            fmt=fmt,
            columns=columns,
        )


# ---- top-level save (--all bulk dump) ----


@app.command("save", no_args_is_help=True)
def save_top_command(
    out_dir: Path = typer.Option(
        ..., "--out-dir", help="Directory to write per-resource files into."
    ),
    all_kinds: bool = typer.Option(False, "--all", help="Save every saveable kind."),
    kind: str | None = typer.Option(
        None, "--kind", help="Limit save to a single kind (e.g. JobTemplate)."
    ),
    organization: str | None = typer.Option(None, "--organization", help="Scope to organization."),
) -> None:
    """Bulk-save resources to a directory.

    ``save --all --out-dir DIR`` writes one file per resource using the
    full identity in the filename so same-named records across
    organizations don't collide:
    ``<Kind>[__<org>][__<parent_kind>__[<parent_org>__]<parent_name>]__<name>.yml``.
    Kinds with read-only fidelity (Credential) are skipped with a
    one-line note.
    """
    if not all_kinds and not kind:
        raise typer.BadParameter("pass --all or --kind")

    with report_errors(), open_context() as ctx:
        target_specs = (
            list(ALL_SPECS)
            if all_kinds
            else [
                ctx.catalog.get(kind)  # type: ignore[arg-type]
            ]
        )
        save = SaveResource(ctx.repo, ctx.fk)
        out_dir.mkdir(parents=True, exist_ok=True)
        written: list[str] = []
        for spec in target_specs:
            if spec.fidelity == "read_only":
                typer.echo(
                    f"skipping {spec.kind}: not roundtrippable in v0",
                    err=True,
                )
                continue
            if "save" not in spec.commands:
                continue
            # Bulk save is "back up everything" by intent. Pass
            # `default_organization=None` so an active default never
            # silently narrows the backup — only an explicit
            # ``--organization`` does.
            scope = scope_for_spec(spec, organization, None)
            records = save.find_all(spec, scope=scope)
            if organization:
                records = _narrow_to_organization(spec, records, organization)
            for record in records:
                resource = save.from_record(spec, record)
                comment = spec.fidelity_note if spec.fidelity != "full" else None
                target = out_dir / _resource_filename(spec.kind, resource.metadata)
                _assert_inside(out_dir, target)
                write_resource(target, resource, header_comment=comment)
                written.append(str(target))
    for path in written:
        typer.echo(path)


_UNSAFE_FILENAME_CHARS = re.compile(r"[/\\\x00-\x1f]")


def _safe_filename_segment(name: str) -> str:
    """Return a filesystem-safe segment derived from an AWX resource name.

    Replaces path separators and ASCII control chars with ``_``, collapses
    leading/trailing dots so we can never produce ``..`` or ``.``, and falls
    back to ``unnamed`` for empty results. The original name remains in the
    saved YAML's metadata.
    """
    if not name:
        return "unnamed"
    cleaned = _UNSAFE_FILENAME_CHARS.sub("_", name).strip(". ")
    return cleaned or "unnamed"


def _assert_inside(parent: Path, target: Path) -> None:
    """Refuse paths that resolve outside the intended parent directory."""
    parent_resolved = parent.resolve()
    try:
        target.resolve().relative_to(parent_resolved)
    except ValueError as exc:  # pragma: no cover — defensive guard
        raise AwxApiError(f"refusing to write {target} — outside {parent_resolved}") from exc


def _narrow_to_organization(
    spec: ResourceSpec,
    records: list[dict[str, Any]],
    organization: str,
) -> list[dict[str, Any]]:
    """Filter parent-scoped kinds (Schedule) by parent's org client-side."""
    if "organization" in spec.identity_keys:
        return records  # already filtered server-side
    if spec.kind != "Schedule":
        return records  # global kinds (Organization, CredentialType) ignore org
    return [
        r
        for r in records
        if (
            ((r.get("summary_fields") or {}).get("unified_job_template") or {}).get(
                "organization_name"
            )
        )
        == organization
    ]


def _resource_filename(kind: str, metadata: Metadata) -> str:
    """Encode the identity tuple in the filename so same-named records don't collide."""
    parts: list[str] = [kind]
    if metadata.parent is not None:
        parts.append(metadata.parent.kind)
        if metadata.parent.organization:
            parts.append(metadata.parent.organization)
        parts.append(metadata.parent.name)
    elif metadata.organization is not None:
        parts.append(metadata.organization)
    parts.append(metadata.name)
    return "__".join(_safe_filename_segment(p) for p in parts) + ".yml"


# ---- jobs (read-only execution records) ----


jobs_app = typer.Typer(name="jobs", help="Inspect AWX jobs.", no_args_is_help=True)


@jobs_app.callback()
def _jobs_callback() -> None:
    """Inspect AWX jobs."""


@jobs_app.command("get", no_args_is_help=True)
def jobs_get(
    job_id: int = typer.Argument(..., help="Job ID."),
    fmt: OutputFormat = typer.Option("yaml", "--format", "-f"),
) -> None:
    """Fetch a single job by id."""
    with report_errors(), open_context() as ctx:
        record = ctx.repo.request("GET", f"jobs/{job_id}/")
    typer.echo(format_output([record], fmt=fmt, columns=[]))


@jobs_app.command("logs", no_args_is_help=True)
def jobs_logs(
    job_id: int = typer.Argument(..., help="Job ID."),
) -> None:
    """Print the job's stdout (plain text from AWX)."""
    with report_errors(), open_context() as ctx:
        text = ctx.repo.request_text("GET", f"jobs/{job_id}/stdout/", params={"format": "txt"})
    typer.echo(text)


@jobs_app.command("wait", no_args_is_help=True)
def jobs_wait(
    job_id: int = typer.Argument(..., help="Job ID."),
    timeout: float | None = typer.Option(
        None, "--timeout", help="Seconds to wait before giving up."
    ),
    fmt: OutputFormat = typer.Option(
        "table", "--format", "-f", help="Output format (json|yaml|table|raw)."
    ),
    columns: ColumnsOption = None,
) -> None:
    """Block until the job reaches a terminal state."""
    with report_errors(), open_context() as ctx:
        record = ctx.repo.request("GET", f"jobs/{job_id}/")
        job = Job.model_validate({**record, "kind": "job"})
        final = WatchJob(ctx.repo)(job, timeout=timeout)
    typer.echo(format_output([final.model_dump()], fmt=fmt, columns=columns))


app.add_typer(jobs_app, name="jobs")


# ---- per-resource sub-apps (factory-generated) ----


for spec in ALL_SPECS:
    sub_app = make_resource_app(spec)
    app.add_typer(sub_app, name=spec.cli_name)
