"""Names ``vulture`` reports as unused that are in fact used.

Commands registered by string, Protocol members, pydantic fields and the like
look dead to a static scan. A name listed here counts as used everywhere. Add
a false positive by hand (``name  # why``); remove a line once its code is gone.
The entries generated when the check was added are a baseline still to triage.
"""

# ruff: noqa

alias_set_command  # unused function (packages/untaped-ansible/src/untaped_ansible/cli/source_alias_commands.py:36)
alias_list_command  # unused function (packages/untaped-ansible/src/untaped_ansible/cli/source_alias_commands.py:65)
alias_remove_command  # unused function (packages/untaped-ansible/src/untaped_ansible/cli/source_alias_commands.py:83)
source_set_command  # unused function (packages/untaped-ansible/src/untaped_ansible/cli/source_commands.py:85)
source_patch_command  # unused function (packages/untaped-ansible/src/untaped_ansible/cli/source_commands.py:142)
source_list_command  # unused function (packages/untaped-ansible/src/untaped_ansible/cli/source_commands.py:249)
source_get_command  # unused function (packages/untaped-ansible/src/untaped_ansible/cli/source_commands.py:263)
source_remove_command  # unused function (packages/untaped-ansible/src/untaped_ansible/cli/source_commands.py:280)
source_status_command  # unused function (packages/untaped-ansible/src/untaped_ansible/cli/source_commands.py:312)
source_refresh_command  # unused function (packages/untaped-ansible/src/untaped_ansible/cli/source_commands.py:350)
root_repo  # unused variable (packages/untaped-ansible/src/untaped_ansible/domain/containment.py:37)
root_ref  # unused variable (packages/untaped-ansible/src/untaped_ansible/domain/containment.py:38)
input_kind  # unused variable (packages/untaped-ansible/src/untaped_ansible/domain/containment.py:43)
input_id  # unused variable (packages/untaped-ansible/src/untaped_ansible/domain/containment.py:44)
input_name  # unused variable (packages/untaped-ansible/src/untaped_ansible/domain/containment.py:45)
_.model_post_init  # unused method (packages/untaped-ansible/src/untaped_ansible/domain/graph.py:47)
__context  # unused variable (packages/untaped-ansible/src/untaped_ansible/domain/graph.py:47)
_.validate_kind_shape  # unused method (packages/untaped-ansible/src/untaped_ansible/domain/graph.py:66)
root_ref  # unused variable (packages/untaped-ansible/src/untaped_ansible/domain/reach.py:48)
_.row_factory  # unused attribute (packages/untaped-ansible/src/untaped_ansible/infrastructure/sqlite_index.py:390)
_._validate_source  # unused method (packages/untaped-ansible/src/untaped_ansible/settings.py:37)
_._normalize_teams  # pydantic field validator (packages/untaped-ansible/src/untaped_ansible/settings.py)
__call__  # unused function (packages/untaped-awx/src/untaped_awx/application/suites/ports.py:79)
__call__  # unused function (packages/untaped-awx/src/untaped_awx/application/suites/ports.py:95)
__call__  # unused function (packages/untaped-awx/src/untaped_awx/application/suites/ports.py:105)
__call__  # unused function (packages/untaped-awx/src/untaped_awx/application/suites/ports.py:114)
copy_command  # unused function (packages/untaped-awx/src/untaped_awx/cli/_copy.py:34)
delete_command  # unused function (packages/untaped-awx/src/untaped_awx/cli/_delete.py:38)
patch_command  # unused function (packages/untaped-awx/src/untaped_awx/cli/_patch.py:29)
rename_command  # unused function (packages/untaped-awx/src/untaped_awx/cli/_rename.py:34)
export_command  # unused function (packages/untaped-awx/src/untaped_awx/cli/_save.py:19)
ping_command  # unused function (packages/untaped-awx/src/untaped_awx/cli/commands.py:68)
schema_command  # unused function (packages/untaped-awx/src/untaped_awx/cli/commands.py:84)
export_top_command  # unused function (packages/untaped-awx/src/untaped_awx/cli/commands.py:173)
jobs_list  # unused function (packages/untaped-awx/src/untaped_awx/cli/commands.py:271)
jobs_get  # unused function (packages/untaped-awx/src/untaped_awx/cli/commands.py:330)
jobs_events  # unused function (packages/untaped-awx/src/untaped_awx/cli/commands.py:355)
jobs_logs  # unused function (packages/untaped-awx/src/untaped_awx/cli/commands.py:576)
jobs_wait  # unused function (packages/untaped-awx/src/untaped_awx/cli/commands.py:650)
exc_type  # unused variable (packages/untaped-awx/src/untaped_awx/cli/context.py:92)
tb  # unused variable (packages/untaped-awx/src/untaped_awx/cli/context.py:94)
_.default_parameter  # unused attribute (packages/untaped-awx/src/untaped_awx/cli/factory.py:39)
jobs_cancel  # unused function (packages/untaped-awx/src/untaped_awx/cli/job_actions.py:52)
jobs_relaunch  # unused function (packages/untaped-awx/src/untaped_awx/cli/job_actions.py:95)
launch_command  # unused function (packages/untaped-awx/src/untaped_awx/cli/launch.py:64)
_.default_parameter  # unused attribute (packages/untaped-awx/src/untaped_awx/cli/membership_commands.py:74)
cmd  # unused function (packages/untaped-awx/src/untaped_awx/cli/membership_commands.py:110)
init_command  # unused function (packages/untaped-awx/src/untaped_awx/cli/suite_commands.py:884)
usage_command  # unused function (packages/untaped-awx/src/untaped_awx/cli/usage_commands.py:45)
nodes_command  # unused function (packages/untaped-awx/src/untaped_awx/cli/workflow_node_commands.py:40)
unreachable_hosts  # unused variable (packages/untaped-awx/src/untaped_awx/domain/case_failure.py:185)
changed_tasks  # unused variable (packages/untaped-awx/src/untaped_awx/domain/case_failure.py:187)
apiVersion  # unused variable (packages/untaped-awx/src/untaped_awx/domain/envelope.py:90)
_._lift_result  # unused method (packages/untaped-awx/src/untaped_awx/domain/job.py:171)
dropped_undeclared_secrets  # unused variable (packages/untaped-awx/src/untaped_awx/domain/outcomes.py:52)
active_node  # unused variable (packages/untaped-awx/src/untaped_awx/domain/ping.py:14)
install_uuid  # unused variable (packages/untaped-awx/src/untaped_awx/domain/ping.py:15)
scope_field_in_value  # unused variable (packages/untaped-awx/src/untaped_awx/domain/spec.py:80)
_._kind_required_unless_polymorphic  # unused method (packages/untaped-awx/src/untaped_awx/domain/spec.py:83)
_._optional_secrets_are_secrets  # unused method (packages/untaped-awx/src/untaped_awx/domain/spec.py:208)
_._choices_required_for_choice_type  # unused method (packages/untaped-awx/src/untaped_awx/domain/suite.py:141)
_._something_to_match  # unused method (packages/untaped-awx/src/untaped_awx/domain/suite.py:311)
_._never_ran_alone  # unused method (packages/untaped-awx/src/untaped_awx/domain/suite.py:496)
_._at_least_one_case  # unused method (packages/untaped-awx/src/untaped_awx/domain/suite.py:632)
_._one_template  # unused method (packages/untaped-awx/src/untaped_awx/domain/suite.py:639)
_._cases_fit_the_template  # unused method (packages/untaped-awx/src/untaped_awx/domain/suite.py:649)
rerun_job_id  # unused variable (packages/untaped-awx/src/untaped_awx/domain/suite.py:766)
hosts_truncated  # unused variable (packages/untaped-awx/src/untaped_awx/domain/suite.py:776)
workflow_job_template  # unused variable (packages/untaped-awx/src/untaped_awx/domain/workflow_graph.py:89)
inventory_source  # unused variable (packages/untaped-awx/src/untaped_awx/domain/workflow_graph.py:91)
system_job_template  # unused variable (packages/untaped-awx/src/untaped_awx/domain/workflow_graph.py:94)
_._one_template  # unused method (packages/untaped-awx/src/untaped_awx/domain/workflow_graph.py:108)
credentials  # unused variable (packages/untaped-awx/src/untaped_awx/domain/workflow_graph.py:162)
instance_groups  # unused variable (packages/untaped-awx/src/untaped_awx/domain/workflow_graph.py:164)
execution_environment  # unused variable (packages/untaped-awx/src/untaped_awx/domain/workflow_graph.py:167)
job_tags  # unused variable (packages/untaped-awx/src/untaped_awx/domain/workflow_graph.py:175)
skip_tags  # unused variable (packages/untaped-awx/src/untaped_awx/domain/workflow_graph.py:176)
forks  # unused variable (packages/untaped-awx/src/untaped_awx/domain/workflow_graph.py:180)
job_slice_count  # unused variable (packages/untaped-awx/src/untaped_awx/domain/workflow_graph.py:181)
always  # unused variable (packages/untaped-awx/src/untaped_awx/domain/workflow_graph.py:198)
_._run_or_approval  # unused method (packages/untaped-awx/src/untaped_awx/domain/workflow_graph.py:203)
workflow_job_template  # unused variable (packages/untaped-awx/src/untaped_awx/domain/workflow_node.py:60)
summary_fields  # unused variable (packages/untaped-awx/src/untaped_awx/domain/workflow_node.py:65)
node_count  # unused variable (packages/untaped-awx/src/untaped_awx/domain/workflow_usage.py:26)
exc_type  # unused variable (packages/untaped-awx/src/untaped_awx/infrastructure/awx_client.py:106)
tb  # unused variable (packages/untaped-awx/src/untaped_awx/infrastructure/awx_client.py:108)
_._api_prefix_shape  # unused method (packages/untaped-awx/src/untaped_awx/settings.py:31)
MAX_TEAM_REPO_QUALIFIERS  # unused variable (packages/untaped-github/src/untaped_github/application/search.py:34)
delete_command  # unused function (packages/untaped-github/src/untaped_github/cli/cache_commands.py:186)
worktree_command  # unused function (packages/untaped-github/src/untaped_github/cli/cache_commands.py:332)
whoami_command  # unused function (packages/untaped-github/src/untaped_github/cli/commands.py:24)
repos_command  # unused function (packages/untaped-github/src/untaped_github/cli/search_commands.py:107)
code_command  # unused function (packages/untaped-github/src/untaped_github/cli/search_commands.py:179)
issues_command  # unused function (packages/untaped-github/src/untaped_github/cli/search_commands.py:249)
users_command  # unused function (packages/untaped-github/src/untaped_github/cli/search_commands.py:332)
_._flatten_repository  # unused method (packages/untaped-github/src/untaped_github/domain/models.py:129)
user_login  # unused variable (packages/untaped-github/src/untaped_github/domain/models.py:199)
is_pull_request  # unused variable (packages/untaped-github/src/untaped_github/domain/models.py:200)
_._flatten_issue  # unused method (packages/untaped-github/src/untaped_github/domain/models.py:207)
exc_type  # unused variable (packages/untaped-github/src/untaped_github/infrastructure/github_client.py:148)
tb  # unused variable (packages/untaped-github/src/untaped_github/infrastructure/github_client.py:150)
whoami_command  # unused function (packages/untaped-jira/src/untaped_jira/cli/commands.py:163)
issue_get_command  # unused function (packages/untaped-jira/src/untaped_jira/cli/commands.py:179)
comment_list_command  # unused function (packages/untaped-jira/src/untaped_jira/cli/commands.py:248)
issue_search_command  # unused function (packages/untaped-jira/src/untaped_jira/cli/commands.py:275)
issue_assigned_command  # unused function (packages/untaped-jira/src/untaped_jira/cli/commands.py:317)
issue_create_command  # unused function (packages/untaped-jira/src/untaped_jira/cli/commands.py:437)
issue_patch_command  # unused function (packages/untaped-jira/src/untaped_jira/cli/commands.py:490)
issue_comment_command  # unused function (packages/untaped-jira/src/untaped_jira/cli/commands.py:574)
issue_transitions_command  # unused function (packages/untaped-jira/src/untaped_jira/cli/commands.py:622)
issue_transition_command  # unused function (packages/untaped-jira/src/untaped_jira/cli/commands.py:648)
link_create_command  # unused function (packages/untaped-jira/src/untaped_jira/cli/commands.py:751)
project_list_command  # unused function (packages/untaped-jira/src/untaped_jira/cli/commands.py:793)
project_get_command  # unused function (packages/untaped-jira/src/untaped_jira/cli/commands.py:816)
board_list_command  # unused function (packages/untaped-jira/src/untaped_jira/cli/commands.py:835)
sprint_list_command  # unused function (packages/untaped-jira/src/untaped_jira/cli/commands.py:873)
email_address  # unused variable (packages/untaped-jira/src/untaped_jira/domain/models.py:47)
api_url  # unused variable (packages/untaped-jira/src/untaped_jira/domain/models.py:63)
priority  # unused variable (packages/untaped-jira/src/untaped_jira/domain/models.py:65)
_._flatten_fields  # unused method (packages/untaped-jira/src/untaped_jira/domain/models.py:67)
api_url  # unused variable (packages/untaped-jira/src/untaped_jira/domain/models.py:97)
_._flatten_jira_comment  # unused method (packages/untaped-jira/src/untaped_jira/domain/models.py:99)
reporter  # unused variable (packages/untaped-jira/src/untaped_jira/domain/models.py:168)
_._flatten_detail_fields  # unused method (packages/untaped-jira/src/untaped_jira/domain/models.py:176)
api_url  # unused variable (packages/untaped-jira/src/untaped_jira/domain/models.py:322)
comment_id  # unused variable (packages/untaped-jira/src/untaped_jira/domain/models.py:324)
linked_key  # unused variable (packages/untaped-jira/src/untaped_jira/domain/models.py:326)
to_status  # unused variable (packages/untaped-jira/src/untaped_jira/domain/models.py:339)
_._flatten_target  # unused method (packages/untaped-jira/src/untaped_jira/domain/models.py:341)
project_type_key  # unused variable (packages/untaped-jira/src/untaped_jira/domain/models.py:357)
api_url  # unused variable (packages/untaped-jira/src/untaped_jira/domain/models.py:370)
start_at  # unused variable (packages/untaped-jira/src/untaped_jira/domain/models.py:381)
end_at  # unused variable (packages/untaped-jira/src/untaped_jira/domain/models.py:384)
goal  # unused variable (packages/untaped-jira/src/untaped_jira/domain/models.py:387)
origin_board_id  # unused variable (packages/untaped-jira/src/untaped_jira/domain/models.py:388)
_._parse_timestamp  # unused method (packages/untaped-jira/src/untaped_jira/domain/models.py:392)
exc_type  # unused variable (packages/untaped-jira/src/untaped_jira/infrastructure/jira_client.py:207)
tb  # unused variable (packages/untaped-jira/src/untaped_jira/infrastructure/jira_client.py:209)
_._prefix_shape  # unused method (packages/untaped-jira/src/untaped_jira/settings.py:33)
_._assigned_jql_not_blank  # unused method (packages/untaped-jira/src/untaped_jira/settings.py:40)
_.pass_  # unused method (packages/untaped-recipe/src/untaped_recipe/_worker/helpers.py:101)
_.fail  # unused method (packages/untaped-recipe/src/untaped_recipe/_worker/helpers.py:105)
_.pass_  # unused method (packages/untaped-recipe/src/untaped_recipe/application/ports.py:122)
_.fail  # unused method (packages/untaped-recipe/src/untaped_recipe/application/ports.py:125)
size_bytes  # unused variable (packages/untaped-recipe/src/untaped_recipe/cli/backup_commands.py:55)
code_generator_class  # unused variable (packages/untaped-recipe/src/untaped_recipe/domain/input_jinja.py:83)
concat  # unused variable (packages/untaped-recipe/src/untaped_recipe/domain/input_jinja.py:84)
_._module_name  # unused method (packages/untaped-recipe/src/untaped_recipe/domain/pack.py:64)
_._recipe_ids  # unused method (packages/untaped-recipe/src/untaped_recipe/domain/pack.py:88)
_._hook_names  # unused method (packages/untaped-recipe/src/untaped_recipe/domain/pack.py:95)
_._safe_relative_path  # unused method (packages/untaped-recipe/src/untaped_recipe/domain/plan.py:57)
_._normalize_input_metadata  # unused method (packages/untaped-recipe/src/untaped_recipe/domain/recipe.py:42)
_._validate_input_spec  # unused method (packages/untaped-recipe/src/untaped_recipe/domain/recipe.py:63)
_._safe_file  # unused method (packages/untaped-recipe/src/untaped_recipe/domain/recipe.py:198)
_._non_empty_files  # unused method (packages/untaped-recipe/src/untaped_recipe/domain/recipe.py:205)
_._safe_files  # unused method (packages/untaped-recipe/src/untaped_recipe/domain/recipe.py:212)
_._non_empty_patterns  # unused method (packages/untaped-recipe/src/untaped_recipe/domain/recipe.py:217)
_._one_file_selector  # unused method (packages/untaped-recipe/src/untaped_recipe/domain/recipe.py:227)
_._optional_needs_named_files  # unused method (packages/untaped-recipe/src/untaped_recipe/domain/recipe.py:245)
_._safe_paths  # unused method (packages/untaped-recipe/src/untaped_recipe/domain/recipe.py:261)
_._safe_paths  # unused method (packages/untaped-recipe/src/untaped_recipe/domain/recipe.py:275)
_._require_assertion  # unused method (packages/untaped-recipe/src/untaped_recipe/domain/testcase.py:20)
_._validate_error_contract  # unused method (packages/untaped-recipe/src/untaped_recipe/domain/testcase.py:37)
block_seq_indent  # unused variable (packages/untaped-recipe/src/untaped_recipe/hook_api.py:25)
explicit_start  # unused variable (packages/untaped-recipe/src/untaped_recipe/hook_api.py:26)
explicit_end  # unused variable (packages/untaped-recipe/src/untaped_recipe/hook_api.py:27)
_plain_mapping_options_are_supported  # unused function (packages/untaped-recipe/src/untaped_recipe/hook_api.py:35)
_typed_options_are_supported  # unused function (packages/untaped-recipe/src/untaped_recipe/hook_api.py:41)
_._shape_matches_status  # unused method (packages/untaped-recipe/src/untaped_recipe/infrastructure/hook_worker_client.py:45)
_.active_count  # unused method (packages/untaped-workspace/src/untaped_workspace/infrastructure/command_runner.py:68)
_clear_for_tests  # unused function (packages/untaped/src/untaped/bootstrap.py:172)
_fail  # unused function (packages/untaped/src/untaped/bootstrap.py:300)
_.end_of_options_delimiter  # unused attribute (packages/untaped/src/untaped/bootstrap.py:360)
_.__signature__  # unused attribute (packages/untaped/src/untaped/bootstrap.py:403)
_.__annotations__  # unused attribute (packages/untaped/src/untaped/bootstrap.py:404)
profile_fields  # unused variable (packages/untaped/src/untaped/capabilities/registry.py:116)
core_violations  # unused function (packages/untaped/src/untaped/conventions/__init__.py:141)
exc_type  # unused variable (packages/untaped/src/untaped/http.py:381)
tb  # unused variable (packages/untaped/src/untaped/http.py:383)
set_command  # unused function (packages/untaped/src/untaped/management/alias.py:78)
show_command  # unused function (packages/untaped/src/untaped/management/capabilities.py:53)
profile_fields  # unused variable (packages/untaped/src/untaped/management/config.py:52)
set_command  # unused function (packages/untaped/src/untaped/management/config.py:168)
unset_command  # unused function (packages/untaped/src/untaped/management/config.py:200)
migrate_command  # registered by @app.command (packages/untaped/src/untaped/management/auth.py)
setup_command  # unused function (packages/untaped/src/untaped/management/setup.py:52)
install_command  # unused function (packages/untaped/src/untaped/management/skills.py:125)
update_command  # unused function (packages/untaped/src/untaped/management/skills.py:178)
_.ttimeoutlen  # unused attribute (packages/untaped/src/untaped/picker/app.py:146)
_pasted  # unused function (packages/untaped/src/untaped/picker/app.py:168)
_typed  # unused function (packages/untaped/src/untaped/picker/app.py:172)
previous_name  # unused variable (packages/untaped/src/untaped/profile/models.py:55)
copied_from  # unused variable (packages/untaped/src/untaped/profile/models.py:56)
reset_profile_override  # unused function (packages/untaped/src/untaped/profile_resolver.py:48)
profile_override  # unused function (packages/untaped/src/untaped/profile_resolver.py:72)
_._own_fields_first  # unused method (packages/untaped/src/untaped/records.py:178)
_.settings_customise_sources  # unused method (packages/untaped/src/untaped/settings.py:120)
dotenv_settings  # unused variable (packages/untaped/src/untaped/settings.py:126)
_.settings_customise_sources  # unused method (packages/untaped/src/untaped/settings.py:391)
dotenv_settings  # unused variable (packages/untaped/src/untaped/settings.py:397)
_.settings_customise_sources  # unused method (packages/untaped/src/untaped/settings.py:461)
dotenv_settings  # unused variable (packages/untaped/src/untaped/settings.py:467)
_._valid_aliases  # unused method (packages/untaped/src/untaped/shell_settings.py:48)
_hermetic_environment  # unused function (packages/untaped/src/untaped/testing/plugin.py:40)
_isolate_config_registry_for_tests  # unused function (packages/untaped/src/untaped/testing/plugin.py:73)
_._known_theme_on_write  # unused method (packages/untaped/src/untaped/theme.py:69)
_.confirm_action  # unused method (packages/untaped/src/untaped/ui.py:230)
_._source_inside_repo  # pydantic field validator (packages/untaped-dotfiles/src/untaped_dotfiles/domain/manifest.py)
_._target_is_home_relative_or_absolute  # pydantic field validator (packages/untaped-dotfiles/src/untaped_dotfiles/domain/manifest.py)
_._merge_has_a_format  # pydantic model validator (packages/untaped-dotfiles/src/untaped_dotfiles/domain/manifest.py)
_._targets_are_unique  # pydantic model validator (packages/untaped-dotfiles/src/untaped_dotfiles/domain/manifest.py)
_._known_version  # pydantic field validator (packages/untaped-dotfiles/src/untaped_dotfiles/domain/manifest.py)
_._item_names  # pydantic field validator (packages/untaped-dotfiles/src/untaped_dotfiles/domain/manifest.py)
subscribed_at  # state.yml record field, read by users (packages/untaped-dotfiles/src/untaped_dotfiles/domain/models.py)
source_commit  # state.yml record field, read by users (packages/untaped-dotfiles/src/untaped_dotfiles/domain/models.py)
applied_at  # state.yml record field, read by users (packages/untaped-dotfiles/src/untaped_dotfiles/domain/models.py)
suggested  # output record field (packages/untaped-dotfiles/src/untaped_dotfiles/domain/records.py)
foreign  # output record field (packages/untaped-dotfiles/src/untaped_dotfiles/domain/records.py)
